#!/usr/bin/env python3
"""Extract glosses for the gold-list lexemes from a wiktextract JSONL dump.

Usage: python3 scripts/extract-glosses.py <path-to-simple-extract.jsonl>

Writes data/lexicon/glosses.yaml: for each (lemma, pos) in the gold lists,
up to MAX_SENSES glosses with one example each. Run locally when refreshing
the dump; the output file is committed so CI and the browser need no dump.
Content is CC BY-SA (Simple English Wiktionary via kaikki.org).
"""
import json
import sys
import pathlib
import datetime

MAX_SENSES = 4
ROOT = pathlib.Path(__file__).resolve().parent.parent
GOLD = ROOT / "data/lexicon/gold"
OUT = ROOT / "data/lexicon/glosses.yaml"

# gold file -> wiktextract pos codes to accept
POS_FOR_FILE = {
    "determinatives.yaml": {"det"},
    "prepositions.yaml": {"prep"},
    "pronouns.yaml": {"pron"},
    "conjunctions.yaml": {"conj"},
}


def yaml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def wanted_lemmas():
    import re
    wanted = {}  # (lemma, pos) preserved per gold source
    for fname, poses in POS_FOR_FILE.items():
        text = (GOLD / fname).read_text()
        lemmas = re.findall(r'^\s+- "?([^"\n]+)"?$', text, re.M)
        # crude but adequate: item lines in gold files are single-level lists
        for lemma in lemmas:
            lemma = lemma.strip().strip('"')
            if lemma and not lemma.startswith("#"):
                for pos in poses:
                    wanted[(lemma, pos)] = fname
    return wanted


def main(dump_path):
    wanted = wanted_lemmas()
    found = {}
    with open(dump_path) as f:
        for line in f:
            e = json.loads(line)
            if e.get("lang_code") != "en":
                continue
            key = (e.get("word", ""), e.get("pos", ""))
            if key not in wanted or key in found:
                continue
            senses = []
            for sense in e.get("senses", [])[:MAX_SENSES]:
                glosses = sense.get("glosses") or []
                if not glosses:
                    continue
                entry = {"gloss": glosses[-1]}
                for ex in sense.get("examples", []):
                    if ex.get("text"):
                        entry["example"] = ex["text"]
                        break
                senses.append(entry)
            if senses:
                found[key] = senses

    lines = [
        "# Glosses for the gold-list lexemes, extracted from Simple English Wiktionary",
        "# (wiktextract via kaikki.org). CC BY-SA. Generated by scripts/extract-glosses.py;",
        "# regenerate when the dump is refreshed. Do not hand-edit.",
        f"extracted: \"{datetime.date.today().isoformat()}\"",
        "source: \"Simple English Wiktionary (kaikki.org simple-extract.jsonl)\"",
        "glosses:",
    ]
    for (lemma, pos), senses in sorted(found.items()):
        lines.append(f"  - lemma: {yaml_str(lemma)}")
        lines.append(f"    pos: {pos}")
        lines.append("    senses:")
        for s in senses:
            lines.append(f"      - gloss: {yaml_str(s['gloss'])}")
            if "example" in s:
                lines.append(f"        example: {yaml_str(s['example'])}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.name}: {len(found)} of {len(wanted)} (lemma,pos) pairs glossed")


if __name__ == "__main__":
    main(sys.argv[1])
